### ISSUE TITLE
Error using with RequireJS

### ISSUE THREAD

**Issue by relu-xz** [federicogfernandez/osom-datepicker#3]
Hi there.

This does not work:

``` javascript
var datepicker = new OsomDatepicker({
...
});

datepicker.initialize();
```

I get this error:

`TypeError: datepicker.initialize is not a function`

This:

``` javascript
console.log(datepicker);
```

Returns:

``` javascript
function OsomDatepicker/OsomDatepickerPublic()
```

But I need a `OsomDatepicker` object.

Do you have a good example with RequireJS?

**Comment by federicogfernandez** [comment]
This is the way to use it with requirejs

`require(['osomdatepicker'], function(OsomDatepicker){
	var datepickerRequire = new OsomDatepicker({
		selector: '#osom-datepicker',
		selectedDates: [new Date()],
		fromDate: new Date(),
		animation: 'horizontal',
		showMultipleDays: true,
		monthNames: [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec' ],
		dayNames: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
		weekStart: 'Monday',
		onDateSelected: function(dates){
			console.log(dates);
		}
	});

	datepickerRequire.initialize();
});`

**Comment by federicogfernandez** [comment]
`require(['osomdatepicker'], function(OsomDatepicker){
				var datepickerRequire = new OsomDatepicker({
					selector: '#osom-datepicker',
					selectedDates: [new Date()],
					fromDate: new Date(),
					animation: 'horizontal',
					showMultipleDays: true,
					monthNames: [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec' ],
					dayNames: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
					weekStart: 'Monday',
					onDateSelected: function(dates){
						console.log(dates);
					}
				});

				datepickerRequire.initialize();
			});`

**Comment by federicogfernandez** [comment]
```require(['osomdatepicker'], function(OsomDatepicker){
				var datepickerRequire = new OsomDatepicker({
					selector: '#osom-datepicker',
					selectedDates: [new Date()],
					fromDate: new Date(),
					animation: 'horizontal',
					showMultipleDays: true,
					monthNames: [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec' ],
					dayNames: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
					weekStart: 'Monday',
					onDateSelected: function(dates){
						console.log(dates);
					}
				});

				datepickerRequire.initialize();
			});```

**Comment by federicogfernandez** [comment]
This should work

``` javascript
require(['osomdatepicker'], function(OsomDatepicker){
    var datepickerRequire = new OsomDatepicker({
        selector: '#osom-datepicker',
        selectedDates: [new Date()],
        fromDate: new Date(),
        animation: 'horizontal',
        showMultipleDays: true,
        monthNames: [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec' ],
        dayNames: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
        weekStart: 'Monday',
        onDateSelected: function(dates){
            console.log(dates);
        }
    });

    datepickerRequire.initialize();
});
```

**Comment by relu-xz** [comment]
Thanks, it does work...It would be a `+1` add it in README.md
